### ISSUE TITLE
AuditTrailManagementAspect should gracefully fail on invalid resolvers

### ISSUE THREAD

**Issue by frett** [apereo/inspektr#1]
Currently if there is an exception thrown by a principal, action, or resource resolver it is propagated up the stack. This means methods that completed successfully may return an exception because auditing failed.

Instead of this behavior I feel we should capture these failures, log them at the error(?) level and return the original response.

**Comment by dima767** [comment]
+1 The auditing should be considered a crosscutting concern and should not interfere with main business transactions. IMO, the main business transaction that the auditing functionality is applied to should be resilient to failures in the auditing components.

Would love to hear other opinions on this. Ping @mmoayyed , @battags , @scalding

**Comment by mmoayyed** [comment]
:+1: yes, I am very much in favor of grace :)

**Comment by battags** [comment]
I think we weirdly need to end up supporting both (at least from Inspektr's perspective; CAS probably doesn't care about both).

Its an auditing framework and sometimes an action should not occur if it can't be logged correctly, and sometimes auditing is a nice-to-have.

Maybe we can add a flag to the annotation to determine behavior.

**Comment by mmoayyed** [comment]
>Its an auditing framework and sometimes an action should not occur if it can't be logged correctly, and sometimes auditing is a nice-to-have.

:+1:

**Comment by frett** [comment]
at the point the audit is occurring the action has already been completed.

**Comment by dima767** [comment]
Yes, the action has occurred, but I see a point of not allowing the main business transaction to complete if there are very strong/strict auditing requirements - no actions should occur in the business system if there is no trail, etc. Financial, government systems, etc. But again, who are we kidding - we expect big financial firms to use our tiny Inspektr?! ;-) Nevertheless, a flag approach would work fine with the default to not propagate audit exception up to main business transactions, etc.

**Comment by battags** [comment]
The action may have taken place, but that doesn't mean its final or should be allowed.

For example, LDAP could have returned true that the user is authenticated, but the exception could still stop the login process.  Or, a save could have occurred but the audit exception would rollback the transaction.

Either way, I think we can easily make everyone happy with a simple flag on the annotation and a check in the code base.  I can look at that this weekend (most likely)

**Comment by battags** [comment]
Apparently I never did so @mmoayyed did.  I like his solution :-)
