### ISSUE TITLE
Consider an alternate syntax for log data

### ISSUE THREAD

**Issue by mmoayyed** [apereo/inspektr#3]
- Single line format
- JSON format

**Comment by battags** [comment]
Single line format:
https://github.com/dima767/inspektr/blob/master/inspektr-audit/src/main/java/com/github/inspektr/audit/support/AbstractStringAuditTrailManager.java

is already done :-)

**Comment by mmoayyed** [comment]
Sweet!

**Comment by dima767** [comment]
wrt JSON format. Is there a particular, concrete use case, or just forward thinking? 

Can some one show what the JSON message would look like?

**Comment by dima767** [comment]
Also, would this JSON formatted audit entry be fed into the slf4j audit manager, still? Would that be useful to have JSON strings in the log files?

**Comment by mmoayyed** [comment]
I'd say, it's a bit of both. Systems such as logstash and splunk work better with JSON data. At some point, CAS may also want to do something with it, don't know. 

And yes I think it should be fed into the manager. By default it may end up in log files, but adopters could choose to push it down to external systems or JPA, etc. 

Very similar to what we have today:

```json
{
   "auditEventXYZ":{
      "who":"...",
      "what":"...",
      "action":"...",
      "application":"...",
      "when":"...",
      "clientIpAddress":"...",
      "serverIpAddress":"..."
   }
}
```

where XYZ would probably be some form of sequence number, so the block can be identified.

**Comment by mmoayyed** [comment]
To be clear, these external systems aren't actually going to *parse* json. They all do pattern recognition and parse text. We should just make it easy for them to parse this data as text via patterns, and also help apps that actually can parse JSON at the same time.
